version: "3.8"
services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: db_exercise
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: passw0rd
    volumes:
      - /home/edu/./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
