version: "3.8"
services:
  mysql:
    image: mysql:5.7.16
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - /home/edu/./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
